import type { CvTheme } from '@/types/jobs'

export const CV_THEMES: CvTheme[] = [
  // ── Single Column ──
  {
    id: 'classic',
    name: 'Classic',
    layout: 'single-column',
    primaryColor: '#1a1a2e',
    secondaryColor: '#16213e',
    accentColor: '#0f3460',
    backgroundColor: '#ffffff',
    fontHeading: 'Georgia, serif',
    fontBody: 'Times New Roman, serif',
    fontSize: 11,
    lineHeight: 1.4,
    sectionSpacing: 1,
    headerStyle: 'centered',
    showPhoto: false,
  },
  {
    id: 'modern',
    name: 'Modern',
    layout: 'single-column',
    primaryColor: '#2d3436',
    secondaryColor: '#636e72',
    accentColor: '#6c5ce7',
    backgroundColor: '#ffffff',
    fontHeading: 'Inter, sans-serif',
    fontBody: 'Inter, sans-serif',
    fontSize: 10,
    lineHeight: 1.5,
    sectionSpacing: 0.8,
    headerStyle: 'left',
    showPhoto: false,
  },
  {
    id: 'minimal',
    name: 'Minimal',
    layout: 'single-column',
    primaryColor: '#000000',
    secondaryColor: '#555555',
    accentColor: '#000000',
    backgroundColor: '#ffffff',
    fontHeading: 'Helvetica, Arial, sans-serif',
    fontBody: 'Helvetica, Arial, sans-serif',
    fontSize: 10,
    lineHeight: 1.4,
    sectionSpacing: 0.6,
    headerStyle: 'left',
    showPhoto: false,
  },
  {
    id: 'elegant',
    name: 'Elegant',
    layout: 'single-column',
    primaryColor: '#1a1a2e',
    secondaryColor: '#4a4a68',
    accentColor: '#c9a227',
    backgroundColor: '#fefefe',
    fontHeading: 'Playfair Display, Georgia, serif',
    fontBody: 'Lato, sans-serif',
    fontSize: 10.5,
    lineHeight: 1.5,
    sectionSpacing: 1,
    headerStyle: 'centered',
    showPhoto: false,
  },
  {
    id: 'swiss',
    name: 'Swiss',
    layout: 'single-column',
    primaryColor: '#111111',
    secondaryColor: '#666666',
    accentColor: '#ff0000',
    backgroundColor: '#ffffff',
    fontHeading: 'Helvetica, Arial, sans-serif',
    fontBody: 'Helvetica, Arial, sans-serif',
    fontSize: 10,
    lineHeight: 1.45,
    sectionSpacing: 0.7,
    headerStyle: 'left',
    showPhoto: false,
  },

  // ── Two Column ──
  {
    id: 'corporate',
    name: 'Corporate',
    layout: 'two-column',
    primaryColor: '#1b2838',
    secondaryColor: '#4a5568',
    accentColor: '#2b6cb0',
    backgroundColor: '#ffffff',
    fontHeading: 'Cambria, serif',
    fontBody: 'Calibri, sans-serif',
    fontSize: 10,
    lineHeight: 1.4,
    sectionSpacing: 0.8,
    headerStyle: 'inline',
    showPhoto: false,
  },
  {
    id: 'ocean',
    name: 'Ocean',
    layout: 'two-column',
    primaryColor: '#1a365d',
    secondaryColor: '#4a6fa5',
    accentColor: '#2196f3',
    backgroundColor: '#ffffff',
    fontHeading: 'Roboto, sans-serif',
    fontBody: 'Roboto, sans-serif',
    fontSize: 10,
    lineHeight: 1.45,
    sectionSpacing: 0.8,
    headerStyle: 'left',
    showPhoto: false,
  },
  {
    id: 'executive',
    name: 'Executive',
    layout: 'two-column',
    primaryColor: '#1a1a1a',
    secondaryColor: '#4a4a4a',
    accentColor: '#c0392b',
    backgroundColor: '#ffffff',
    fontHeading: 'Georgia, serif',
    fontBody: 'Calibri, sans-serif',
    fontSize: 10.5,
    lineHeight: 1.4,
    sectionSpacing: 0.9,
    headerStyle: 'inline',
    showPhoto: false,
  },

  // ── Sidebar (right) ──
  {
    id: 'creative',
    name: 'Creative',
    layout: 'sidebar',
    primaryColor: '#2c3e50',
    secondaryColor: '#7f8c8d',
    accentColor: '#e74c3c',
    backgroundColor: '#ffffff',
    fontHeading: 'Montserrat, sans-serif',
    fontBody: 'Open Sans, sans-serif',
    fontSize: 10,
    lineHeight: 1.5,
    sectionSpacing: 0.8,
    headerStyle: 'left',
    showPhoto: true,
  },
  {
    id: 'fresh',
    name: 'Fresh',
    layout: 'sidebar',
    primaryColor: '#2d3e50',
    secondaryColor: '#5a7a8a',
    accentColor: '#27ae60',
    backgroundColor: '#ffffff',
    fontHeading: 'Inter, sans-serif',
    fontBody: 'Inter, sans-serif',
    fontSize: 10,
    lineHeight: 1.5,
    sectionSpacing: 0.8,
    headerStyle: 'left',
    showPhoto: false,
  },

  // ── Left Sidebar ──
  {
    id: 'professional',
    name: 'Professional',
    layout: 'left-sidebar',
    primaryColor: '#2c3e50',
    secondaryColor: '#5d6d7e',
    accentColor: '#34495e',
    backgroundColor: '#ffffff',
    fontHeading: 'Roboto, sans-serif',
    fontBody: 'Roboto, sans-serif',
    fontSize: 10,
    lineHeight: 1.45,
    sectionSpacing: 0.8,
    headerStyle: 'left',
    showPhoto: true,
  },
  {
    id: 'nordic',
    name: 'Nordic',
    layout: 'left-sidebar',
    primaryColor: '#2e3440',
    secondaryColor: '#4c566a',
    accentColor: '#5e81ac',
    backgroundColor: '#ffffff',
    fontHeading: 'Inter, sans-serif',
    fontBody: 'Inter, sans-serif',
    fontSize: 10,
    lineHeight: 1.5,
    sectionSpacing: 0.8,
    headerStyle: 'left',
    showPhoto: false,
  },
  {
    id: 'rose',
    name: 'Rosé',
    layout: 'left-sidebar',
    primaryColor: '#3d2c2e',
    secondaryColor: '#6d5c5e',
    accentColor: '#c2185b',
    backgroundColor: '#ffffff',
    fontHeading: 'Playfair Display, Georgia, serif',
    fontBody: 'Lato, sans-serif',
    fontSize: 10,
    lineHeight: 1.5,
    sectionSpacing: 0.8,
    headerStyle: 'centered',
    showPhoto: true,
  },

  // ── Compact ──
  {
    id: 'dense',
    name: 'Dense',
    layout: 'compact',
    primaryColor: '#222222',
    secondaryColor: '#555555',
    accentColor: '#333333',
    backgroundColor: '#ffffff',
    fontHeading: 'Helvetica, Arial, sans-serif',
    fontBody: 'Helvetica, Arial, sans-serif',
    fontSize: 9,
    lineHeight: 1.3,
    sectionSpacing: 0.4,
    headerStyle: 'inline',
    showPhoto: false,
  },
  {
    id: 'tech',
    name: 'Tech',
    layout: 'compact',
    primaryColor: '#1e1e1e',
    secondaryColor: '#6b7280',
    accentColor: '#10b981',
    backgroundColor: '#ffffff',
    fontHeading: 'JetBrains Mono, monospace',
    fontBody: 'Inter, sans-serif',
    fontSize: 9.5,
    lineHeight: 1.35,
    sectionSpacing: 0.5,
    headerStyle: 'left',
    showPhoto: false,
  },

  // ── Timeline ──
  {
    id: 'timeline',
    name: 'Timeline',
    layout: 'timeline',
    primaryColor: '#2d3436',
    secondaryColor: '#636e72',
    accentColor: '#6c5ce7',
    backgroundColor: '#ffffff',
    fontHeading: 'Inter, sans-serif',
    fontBody: 'Inter, sans-serif',
    fontSize: 10,
    lineHeight: 1.5,
    sectionSpacing: 0.8,
    headerStyle: 'left',
    showPhoto: false,
  },
  {
    id: 'sunset',
    name: 'Sunset',
    layout: 'timeline',
    primaryColor: '#3d2c2c',
    secondaryColor: '#7a6565',
    accentColor: '#e67e22',
    backgroundColor: '#fffefa',
    fontHeading: 'Georgia, serif',
    fontBody: 'Open Sans, sans-serif',
    fontSize: 10.5,
    lineHeight: 1.5,
    sectionSpacing: 0.9,
    headerStyle: 'centered',
    showPhoto: false,
  },
  {
    id: 'midnight',
    name: 'Midnight',
    layout: 'timeline',
    primaryColor: '#e0e0e0',
    secondaryColor: '#9e9e9e',
    accentColor: '#7c4dff',
    backgroundColor: '#1a1a2e',
    fontHeading: 'Inter, sans-serif',
    fontBody: 'Inter, sans-serif',
    fontSize: 10,
    lineHeight: 1.5,
    sectionSpacing: 0.8,
    headerStyle: 'left',
    showPhoto: false,
  },
  {
    id: 'slate',
    name: 'Slate',
    layout: 'single-column',
    primaryColor: '#e2e8f0',
    secondaryColor: '#94a3b8',
    accentColor: '#38bdf8',
    backgroundColor: '#0f172a',
    fontHeading: 'Inter, sans-serif',
    fontBody: 'Inter, sans-serif',
    fontSize: 10,
    lineHeight: 1.45,
    sectionSpacing: 0.8,
    headerStyle: 'left',
    showPhoto: false,
  },
]

export const DEFAULT_THEME = CV_THEMES[1] // Modern

export const FONT_OPTIONS = [
  { label: 'Inter', value: 'Inter, sans-serif' },
  { label: 'Helvetica', value: 'Helvetica, Arial, sans-serif' },
  { label: 'Georgia', value: 'Georgia, serif' },
  { label: 'Times New Roman', value: 'Times New Roman, serif' },
  { label: 'Montserrat', value: 'Montserrat, sans-serif' },
  { label: 'Open Sans', value: 'Open Sans, sans-serif' },
  { label: 'Cambria', value: 'Cambria, serif' },
  { label: 'Calibri', value: 'Calibri, sans-serif' },
  { label: 'Roboto', value: 'Roboto, sans-serif' },
  { label: 'Lato', value: 'Lato, sans-serif' },
  { label: 'Playfair Display', value: 'Playfair Display, Georgia, serif' },
  { label: 'JetBrains Mono', value: 'JetBrains Mono, monospace' },
  { label: 'Source Sans Pro', value: 'Source Sans Pro, sans-serif' },
  { label: 'Merriweather', value: 'Merriweather, serif' },
  { label: 'Raleway', value: 'Raleway, sans-serif' },
]
