import type { CvTheme, CvTemplateId } from '@/types/jobs'

export const TEMPLATE_INFO: Record<CvTemplateId, { label: string; description: string }> = {
  'classic': { label: 'Classic', description: 'Traditional single-column with centered header and underlined sections' },
  'modern-left': { label: 'Modern Left', description: 'Clean left-aligned header, bold section bars, tight layout' },
  'bold-sidebar': { label: 'Bold Sidebar', description: 'Full-height dark sidebar with photo, skills & contact. Main content right' },
  'executive-banner': { label: 'Executive Banner', description: 'Large colored header banner with name/title, two-column body below' },
  'minimal-two-col': { label: 'Minimal Two-Col', description: 'Narrow left column for dates, wide right for content. Ultra clean' },
  'timeline': { label: 'Timeline', description: 'Vertical timeline with dots and lines connecting experience entries' },
  'compact-ats': { label: 'Compact ATS', description: 'Dense single-column optimized for ATS scanners. No colors, max content' },
  'magazine': { label: 'Magazine', description: 'Editorial layout with large header, pull-quotes, and card-style sections' },
}

export const CV_THEMES: CvTheme[] = [
  // ── Classic template ──
  {
    id: 'classic-navy',
    name: 'Classic Navy',
    template: 'classic',
    primaryColor: '#1a1a2e',
    secondaryColor: '#4a4a68',
    accentColor: '#0f3460',
    backgroundColor: '#ffffff',
    fontHeading: 'Georgia, serif',
    fontBody: 'Times New Roman, serif',
    fontSize: 11,
    lineHeight: 1.4,
    sectionSpacing: 1,
    showPhoto: false,
  },
  {
    id: 'classic-warm',
    name: 'Classic Warm',
    template: 'classic',
    primaryColor: '#3d2c2c',
    secondaryColor: '#6d5c5e',
    accentColor: '#8b4513',
    backgroundColor: '#fffdf8',
    fontHeading: 'Playfair Display, Georgia, serif',
    fontBody: 'Lato, sans-serif',
    fontSize: 11,
    lineHeight: 1.45,
    sectionSpacing: 1,
    showPhoto: false,
  },

  // ── Modern Left template ──
  {
    id: 'modern-purple',
    name: 'Modern Purple',
    template: 'modern-left',
    primaryColor: '#2d3436',
    secondaryColor: '#636e72',
    accentColor: '#6c5ce7',
    backgroundColor: '#ffffff',
    fontHeading: 'Inter, sans-serif',
    fontBody: 'Inter, sans-serif',
    fontSize: 10,
    lineHeight: 1.5,
    sectionSpacing: 0.8,
    showPhoto: false,
  },
  {
    id: 'modern-teal',
    name: 'Modern Teal',
    template: 'modern-left',
    primaryColor: '#1a202c',
    secondaryColor: '#4a5568',
    accentColor: '#0d9488',
    backgroundColor: '#ffffff',
    fontHeading: 'Roboto, sans-serif',
    fontBody: 'Roboto, sans-serif',
    fontSize: 10,
    lineHeight: 1.5,
    sectionSpacing: 0.8,
    showPhoto: false,
  },

  // ── Bold Sidebar template ──
  {
    id: 'sidebar-dark',
    name: 'Bold Dark',
    template: 'bold-sidebar',
    primaryColor: '#e0e0e0',
    secondaryColor: '#9e9e9e',
    accentColor: '#f39c12',
    backgroundColor: '#2c3e50',
    fontHeading: 'Montserrat, sans-serif',
    fontBody: 'Open Sans, sans-serif',
    fontSize: 10,
    lineHeight: 1.5,
    sectionSpacing: 0.8,
    showPhoto: true,
  },
  {
    id: 'sidebar-blue',
    name: 'Bold Blue',
    template: 'bold-sidebar',
    primaryColor: '#f0f0f0',
    secondaryColor: '#b0bec5',
    accentColor: '#64ffda',
    backgroundColor: '#1a237e',
    fontHeading: 'Inter, sans-serif',
    fontBody: 'Inter, sans-serif',
    fontSize: 10,
    lineHeight: 1.5,
    sectionSpacing: 0.8,
    showPhoto: true,
  },
  {
    id: 'sidebar-rose',
    name: 'Bold Rosé',
    template: 'bold-sidebar',
    primaryColor: '#f5f5f5',
    secondaryColor: '#ccc',
    accentColor: '#ff6b6b',
    backgroundColor: '#3d2c2e',
    fontHeading: 'Playfair Display, Georgia, serif',
    fontBody: 'Lato, sans-serif',
    fontSize: 10,
    lineHeight: 1.5,
    sectionSpacing: 0.8,
    showPhoto: true,
  },

  // ── Executive Banner template ──
  {
    id: 'exec-navy',
    name: 'Executive Navy',
    template: 'executive-banner',
    primaryColor: '#1b2838',
    secondaryColor: '#4a5568',
    accentColor: '#2b6cb0',
    backgroundColor: '#ffffff',
    fontHeading: 'Cambria, serif',
    fontBody: 'Calibri, sans-serif',
    fontSize: 10,
    lineHeight: 1.4,
    sectionSpacing: 0.8,
    showPhoto: false,
  },
  {
    id: 'exec-burgundy',
    name: 'Executive Burgundy',
    template: 'executive-banner',
    primaryColor: '#1a1a1a',
    secondaryColor: '#4a4a4a',
    accentColor: '#800020',
    backgroundColor: '#ffffff',
    fontHeading: 'Georgia, serif',
    fontBody: 'Calibri, sans-serif',
    fontSize: 10.5,
    lineHeight: 1.4,
    sectionSpacing: 0.9,
    showPhoto: false,
  },

  // ── Minimal Two-Col template ──
  {
    id: 'min2col-mono',
    name: 'Minimal Mono',
    template: 'minimal-two-col',
    primaryColor: '#111111',
    secondaryColor: '#666666',
    accentColor: '#111111',
    backgroundColor: '#ffffff',
    fontHeading: 'Helvetica, Arial, sans-serif',
    fontBody: 'Helvetica, Arial, sans-serif',
    fontSize: 10,
    lineHeight: 1.4,
    sectionSpacing: 0.7,
    showPhoto: false,
  },
  {
    id: 'min2col-accent',
    name: 'Minimal Accent',
    template: 'minimal-two-col',
    primaryColor: '#222222',
    secondaryColor: '#666666',
    accentColor: '#e74c3c',
    backgroundColor: '#ffffff',
    fontHeading: 'Inter, sans-serif',
    fontBody: 'Inter, sans-serif',
    fontSize: 10,
    lineHeight: 1.4,
    sectionSpacing: 0.7,
    showPhoto: false,
  },

  // ── Timeline template ──
  {
    id: 'timeline-purple',
    name: 'Timeline Purple',
    template: 'timeline',
    primaryColor: '#2d3436',
    secondaryColor: '#636e72',
    accentColor: '#6c5ce7',
    backgroundColor: '#ffffff',
    fontHeading: 'Inter, sans-serif',
    fontBody: 'Inter, sans-serif',
    fontSize: 10,
    lineHeight: 1.5,
    sectionSpacing: 0.8,
    showPhoto: false,
  },
  {
    id: 'timeline-green',
    name: 'Timeline Green',
    template: 'timeline',
    primaryColor: '#1a202c',
    secondaryColor: '#4a5568',
    accentColor: '#10b981',
    backgroundColor: '#ffffff',
    fontHeading: 'Roboto, sans-serif',
    fontBody: 'Roboto, sans-serif',
    fontSize: 10,
    lineHeight: 1.45,
    sectionSpacing: 0.8,
    showPhoto: false,
  },

  // ── Compact ATS template ──
  {
    id: 'ats-plain',
    name: 'ATS Plain',
    template: 'compact-ats',
    primaryColor: '#000000',
    secondaryColor: '#333333',
    accentColor: '#000000',
    backgroundColor: '#ffffff',
    fontHeading: 'Arial, sans-serif',
    fontBody: 'Arial, sans-serif',
    fontSize: 10,
    lineHeight: 1.3,
    sectionSpacing: 0.4,
    showPhoto: false,
  },
  {
    id: 'ats-modern',
    name: 'ATS Modern',
    template: 'compact-ats',
    primaryColor: '#1a1a1a',
    secondaryColor: '#555555',
    accentColor: '#2563eb',
    backgroundColor: '#ffffff',
    fontHeading: 'Calibri, sans-serif',
    fontBody: 'Calibri, sans-serif',
    fontSize: 10,
    lineHeight: 1.35,
    sectionSpacing: 0.5,
    showPhoto: false,
  },

  // ── Magazine template (accent should be dark — header text is white) ──
  {
    id: 'magazine-orange',
    name: 'Magazine Warm',
    template: 'magazine',
    primaryColor: '#2d2d2d',
    secondaryColor: '#6b6b6b',
    accentColor: '#e67e22',
    backgroundColor: '#ffffff',
    fontHeading: 'Playfair Display, Georgia, serif',
    fontBody: 'Open Sans, sans-serif',
    fontSize: 10,
    lineHeight: 1.5,
    sectionSpacing: 0.8,
    showPhoto: true,
  },
  {
    id: 'magazine-blue',
    name: 'Magazine Cool',
    template: 'magazine',
    primaryColor: '#1a1a2e',
    secondaryColor: '#555577',
    accentColor: '#3498db',
    backgroundColor: '#ffffff',
    fontHeading: 'Montserrat, sans-serif',
    fontBody: 'Lato, sans-serif',
    fontSize: 10,
    lineHeight: 1.5,
    sectionSpacing: 0.8,
    showPhoto: true,
  },
]

export const DEFAULT_THEME = CV_THEMES[2] // Modern Purple

export const FONT_OPTIONS = [
  { label: 'Inter', value: 'Inter, sans-serif' },
  { label: 'Helvetica', value: 'Helvetica, Arial, sans-serif' },
  { label: 'Arial', value: 'Arial, sans-serif' },
  { label: 'Georgia', value: 'Georgia, serif' },
  { label: 'Times New Roman', value: 'Times New Roman, serif' },
  { label: 'Montserrat', value: 'Montserrat, sans-serif' },
  { label: 'Open Sans', value: 'Open Sans, sans-serif' },
  { label: 'Cambria', value: 'Cambria, serif' },
  { label: 'Calibri', value: 'Calibri, sans-serif' },
  { label: 'Roboto', value: 'Roboto, sans-serif' },
  { label: 'Lato', value: 'Lato, sans-serif' },
  { label: 'Playfair Display', value: 'Playfair Display, Georgia, serif' },
  { label: 'JetBrains Mono', value: 'JetBrains Mono, monospace' },
  { label: 'Merriweather', value: 'Merriweather, serif' },
  { label: 'Raleway', value: 'Raleway, sans-serif' },
]
