import type { CvTheme } from '@/types/jobs'

export const CV_THEMES: CvTheme[] = [
  {
    id: 'classic',
    name: 'Classic',
    layout: 'single-column',
    primaryColor: '#1a1a2e',
    secondaryColor: '#16213e',
    accentColor: '#0f3460',
    backgroundColor: '#ffffff',
    fontHeading: 'Georgia, serif',
    fontBody: 'Times New Roman, serif',
    fontSize: 11,
    lineHeight: 1.4,
    sectionSpacing: 1,
    headerStyle: 'centered',
    showPhoto: false,
  },
  {
    id: 'modern',
    name: 'Modern',
    layout: 'single-column',
    primaryColor: '#2d3436',
    secondaryColor: '#636e72',
    accentColor: '#6c5ce7',
    backgroundColor: '#ffffff',
    fontHeading: 'Inter, sans-serif',
    fontBody: 'Inter, sans-serif',
    fontSize: 10,
    lineHeight: 1.5,
    sectionSpacing: 0.8,
    headerStyle: 'left',
    showPhoto: false,
  },
  {
    id: 'minimal',
    name: 'Minimal',
    layout: 'single-column',
    primaryColor: '#000000',
    secondaryColor: '#555555',
    accentColor: '#000000',
    backgroundColor: '#ffffff',
    fontHeading: 'Helvetica, Arial, sans-serif',
    fontBody: 'Helvetica, Arial, sans-serif',
    fontSize: 10,
    lineHeight: 1.4,
    sectionSpacing: 0.6,
    headerStyle: 'left',
    showPhoto: false,
  },
  {
    id: 'creative',
    name: 'Creative',
    layout: 'sidebar',
    primaryColor: '#2c3e50',
    secondaryColor: '#7f8c8d',
    accentColor: '#e74c3c',
    backgroundColor: '#ffffff',
    fontHeading: 'Montserrat, sans-serif',
    fontBody: 'Open Sans, sans-serif',
    fontSize: 10,
    lineHeight: 1.5,
    sectionSpacing: 0.8,
    headerStyle: 'left',
    showPhoto: true,
  },
  {
    id: 'corporate',
    name: 'Corporate',
    layout: 'two-column',
    primaryColor: '#1b2838',
    secondaryColor: '#4a5568',
    accentColor: '#2b6cb0',
    backgroundColor: '#ffffff',
    fontHeading: 'Cambria, serif',
    fontBody: 'Calibri, sans-serif',
    fontSize: 10,
    lineHeight: 1.4,
    sectionSpacing: 0.8,
    headerStyle: 'inline',
    showPhoto: false,
  },
]

export const DEFAULT_THEME = CV_THEMES[1] // Modern

export const FONT_OPTIONS = [
  { label: 'Inter', value: 'Inter, sans-serif' },
  { label: 'Helvetica', value: 'Helvetica, Arial, sans-serif' },
  { label: 'Georgia', value: 'Georgia, serif' },
  { label: 'Times New Roman', value: 'Times New Roman, serif' },
  { label: 'Montserrat', value: 'Montserrat, sans-serif' },
  { label: 'Open Sans', value: 'Open Sans, sans-serif' },
  { label: 'Cambria', value: 'Cambria, serif' },
  { label: 'Calibri', value: 'Calibri, sans-serif' },
  { label: 'Roboto', value: 'Roboto, sans-serif' },
  { label: 'Lato', value: 'Lato, sans-serif' },
]
